export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const ACCOUNT_TYPE = 'ACCOUNT_TYPE';

export const USER_ACTIVATE_REQUEST = 'USER_ACTIVATE_REQUEST';
export const USER_ACTIVATE_SUCCESS = 'USER_ACTIVATE_SUCCESS';
export const USER_ACTIVATE_FAILURE = 'USER_ACTIVATE_FAILURE';
